set(QCLASH_BASEDIR_COMPONENTS ${CMAKE_SOURCE_DIR}/src/components)
set(QCLASH_BASEDIR_CORE ${CMAKE_SOURCE_DIR}/src/core)
set(QCLASH_BASEDIR_BASE ${CMAKE_SOURCE_DIR}/src/base)

set(QCLASH_BASE_SOURCES
    ${QCLASH_BASEDIR_BASE}/QvBaseApplication.cpp
    ${QCLASH_BASEDIR_BASE}/QvBaseApplication.hpp
    ${CMAKE_SOURCE_DIR}/src/ui/QvPlatformApplication.cpp
    ${CMAKE_SOURCE_DIR}/src/ui/QvPlatformApplication.hpp
    ${QCLASH_BASEDIR_BASE}/JsonHelpers.hpp
    ${QCLASH_BASEDIR_BASE}/models/CoreObjectModels.hpp
    ${QCLASH_BASEDIR_BASE}/models/QvComplexConfigModels.hpp
    ${QCLASH_BASEDIR_BASE}/models/QvConfigIdentifier.hpp
    ${QCLASH_BASEDIR_BASE}/models/QvCoreSettings.hpp
    ${QCLASH_BASEDIR_BASE}/models/QvRuntimeConfig.hpp
    ${QCLASH_BASEDIR_BASE}/models/QvSafeType.hpp
    ${QCLASH_BASEDIR_BASE}/models/QvSettingsObject.hpp
    ${QCLASH_BASEDIR_BASE}/models/QvStartupConfig.hpp
    ${QCLASH_BASEDIR_BASE}/QvBase.hpp
    ${QCLASH_BASEDIR_BASE}/QvFeatures.hpp
    ${QCLASH_BASEDIR_BASE}/QvLog.hpp
    ${CMAKE_SOURCE_DIR}/src/utils/HTTPRequestHelper.cpp
    ${CMAKE_SOURCE_DIR}/src/utils/HTTPRequestHelper.hpp
    ${CMAKE_SOURCE_DIR}/src/utils/QvHelpers.cpp
    ${CMAKE_SOURCE_DIR}/src/utils/QvHelpers.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/geosite/QvGeositeReader.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/geosite/QvGeositeReader.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/LatencyTest.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/LatencyTest.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/translations/QvTranslator.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/translations/QvTranslator.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/LatencyTestThread.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/LatencyTestThread.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/TCPing.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/TCPing.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/RealPing.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/RealPing.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/DNSBase.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/win/ICMPPing.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/win/ICMPPing.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/unix/ICMPPing.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/latency/unix/ICMPPing.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/ntp/QvNTPClient.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/ntp/QvNTPClient.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/plugins/QvPluginHost.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/plugins/QvPluginHost.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/port/QvPortDetector.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/port/QvPortDetector.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/proxy/QvProxyConfigurator.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/proxy/QvProxyConfigurator.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/route/RouteSchemeIO.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/route/RouteSchemeIO.hpp
    ${QCLASH_BASEDIR_COMPONENTS}/update/UpdateChecker.cpp
    ${QCLASH_BASEDIR_COMPONENTS}/update/UpdateChecker.hpp
    ${QCLASH_BASEDIR_CORE}/connection/ConnectionIO.cpp
    ${QCLASH_BASEDIR_CORE}/connection/ConnectionIO.hpp
    ${QCLASH_BASEDIR_CORE}/connection/Generation.hpp
    ${QCLASH_BASEDIR_CORE}/connection/generation/final.cpp
    ${QCLASH_BASEDIR_CORE}/connection/generation/inbounds.cpp
    ${QCLASH_BASEDIR_CORE}/connection/generation/outbounds.cpp
    ${QCLASH_BASEDIR_CORE}/connection/generation/filters.cpp
    ${QCLASH_BASEDIR_CORE}/connection/generation/routing.cpp
    ${QCLASH_BASEDIR_CORE}/connection/generation/misc.cpp
    ${QCLASH_BASEDIR_CORE}/connection/Serialization.cpp
    ${QCLASH_BASEDIR_CORE}/connection/Serialization.hpp
    ${QCLASH_BASEDIR_CORE}/connection/serialization/ss.cpp
    ${QCLASH_BASEDIR_CORE}/connection/serialization/ssd.cpp
    ${QCLASH_BASEDIR_CORE}/connection/serialization/vmess.cpp
    ${QCLASH_BASEDIR_CORE}/connection/serialization/vmess_new.cpp
    ${QCLASH_BASEDIR_CORE}/CoreUtils.cpp
    ${QCLASH_BASEDIR_CORE}/CoreUtils.hpp
    ${QCLASH_BASEDIR_CORE}/handler/ConfigHandler.cpp
    ${QCLASH_BASEDIR_CORE}/handler/ConfigHandler.hpp
    ${QCLASH_BASEDIR_CORE}/handler/KernelInstanceHandler.cpp
    ${QCLASH_BASEDIR_CORE}/handler/KernelInstanceHandler.hpp
    ${QCLASH_BASEDIR_CORE}/handler/RouteHandler.cpp
    ${QCLASH_BASEDIR_CORE}/handler/RouteHandler.hpp
    ${QCLASH_BASEDIR_CORE}/kernel/APIBackend.cpp
    ${QCLASH_BASEDIR_CORE}/kernel/APIBackend.hpp
    ${QCLASH_BASEDIR_CORE}/kernel/QvKernelABIChecker.cpp
    ${QCLASH_BASEDIR_CORE}/kernel/QvKernelABIChecker.hpp
    ${QCLASH_BASEDIR_CORE}/kernel/KernelInteractions.cpp
    ${QCLASH_BASEDIR_CORE}/kernel/KernelInteractions.hpp
    ${QCLASH_BASEDIR_CORE}/settings/SettingsBackend.cpp
    ${QCLASH_BASEDIR_CORE}/settings/SettingsBackend.hpp
    ${QCLASH_BASEDIR_CORE}/settings/SettingsUpgrade.cpp
    )
