if(NOT QVMESSOCKET_PLATFORM_LIBS_BIN_PREFIX)
    set(QVMESSOCKET_PLATFORM_LIBS_BIN_PREFIX ${QVMESSOCKET_PLATFORM_LIBS_PREFIX}/tools)
endif()

list(APPEND CMAKE_PROGRAM_PATH
    ${QVMESSOCKET_PLATFORM_LIBS_BIN_PREFIX}/
    ${QVMESSOCKET_PLATFORM_LIBS_BIN_PREFIX}/grpc/
    ${QVMESSOCKET_PLATFORM_LIBS_BIN_PREFIX}/protobuf/
    ${QVMESSOCKET_PLATFORM_LIBS_BIN_PREFIX}/openssl/
    )

message("CMAKE_PROGRAM_PATH=${CMAKE_PROGRAM_PATH}")

list(APPEND CMAKE_PREFIX_PATH ${QVMESSOCKET_PLATFORM_LIBS_PREFIX})
link_directories(${QVMESSOCKET_PLATFORM_LIBS_PREFIX}/lib)
list(APPEND CMAKE_FIND_ROOT_PATH ${QVMESSOCKET_PLATFORM_LIBS_PREFIX})
